server:
  context-path: /api
  port: 7001

management:
  port: 7071
  security.enabled: false

spring:
  application:
    name: stock-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost