server:
  #context-path: /stock
  port: 7001

management:
  port: 7071
  security.enabled: false

spring:
  application:
    name: stock-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/
  instance:
    hostname: localhost