server:
  context-path: /zuul
  port: 7003

management:
  port: 7073
  security.enabled: false

spring:
  application:
    name: zuul-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/
  instance:
    hostname: localhost
