server:
  context-path: /zuul
  port: 7003

management:
  port: 7073
  security.enabled: false

spring:
  application:
    name: zuul-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/
  instance:
    hostname: localhost

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      serviceId: DB-SERVICE
      #url: http://localhost:7000
    stock-service:
      path: /stock-service/**
      serviceId: STOCK-SERVICE
