server:
  #context-path: /eureka
  port: 7002

management:
  port: 7072
  security.enabled: false

spring:
  application:
    name: eureka-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
